---
- name: Collect local admin users
  set_fact:
    _local_admins: "{{ assignments | map(attribute='rand_user') | unique | list }}"

- name: Add random domain users to local admins
  ansible.windows.win_powershell:
    script: |
      $users = '{{ _local_admins | to_json }}' | ConvertFrom-Json
      foreach ($user in $users) {
        Add-LocalGroupMember -Group Administrators -Member "{{ NetBIOS }}\$user" -ErrorAction SilentlyContinue
      }
