---
- name: Pick random local misconfig
  set_fact:
    misconfig: "{{ Local_Misconfigs | random }}"

- ansible.builtin.include_tasks: "{{ misconfig }}"

- name: Create killswitch file for local misconfigs
  ansible.windows.win_file:
    path: C:\users\{{ ansible_facts['user_id'] }}\Documents\lmisconfigs.txt
    state: touch
