---
# Give every computer 1x local misconfig
- name: Pick random local misconfig
  set_fact:
    misconfig: "{{ Local_Misconfigs | random }}"

# Give every computer 1x misconfig
- include_tasks: "{{ misconfig }}"


- name: Create killswitch file for local misconfigs
  ansible.windows.win_file:
    path: C:\users\{{ ansible_user_id }}\Documents\lmisconfigs.txt
    state: touch