---
- include_tasks: pre_checks.yml

- include_tasks: domain.yml
  when: domain_joined == false
  
- include_tasks: ca.yml

- include_tasks: create_certs.yml
  when: cert_exists == false

- include_tasks: "{{ Local_Misconfig_Path }}"
  when: lmisconfigs_exist == false