---
## Domain
- name: Checking if domain joined
  set_fact:
    domain_joined: "{{ Domain in ansible_windows_domain }}"




### Certificates Created
# Tried doing with Get-CATemplate but trying to compare 2 lists if a pain... will come back to this
- name: Setting cert_exists to false
  set_fact:
    cert_exists: false

- name: Check if certificate template is present
  win_shell: |
    Get-CATemplate | select Name
  register: template_info

- name: Checking if cert exists
  set_fact:
    cert_exists: true
  when: item in template_info.stdout_lines | join(",")
  loop: "{{ Certs | regex_replace('\\s') }}"

### Local Misconfigs
- name: Set lmisconfigs_exist to false
  set_fact:
    lmisconfigs_exist: true

- name: Check for local misconfigs killswitch file 
  block:
    - name: Local Misconfig killswitch
      ansible.windows.win_file:
        path: C:\users\{{ ansible_user_id }}\Documents\lmisconfigs.txt
        state: file

  rescue:
    - name: Local Misconfig killswitch not found
      set_fact:
        lmisconfigs_exist: false