---
######## LINUX
- hosts: attacker
  roles:
    - attacker

- hosts: teamserver
  roles:
    - teamserver

- hosts: redirector
  roles:
    - redirector

######## WINDOWS
- hosts: dc:exchange:iis:cert:fileserver:workstation
  tasks:
    - name: Disable Windows Firewall (all profiles)
      ansible.windows.win_powershell:
        script: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

- hosts: dc
  serial: 1
  roles:
    - windows/servers/dc

- hosts: exchange
  roles:
    - windows/servers/exchange

- hosts: iis
  roles:
    - windows/servers/iis

- hosts: cert
  roles:
    - windows/servers/ca

- hosts: fileserver
  roles:
    - windows/servers/fileserver

- hosts: workstation
  roles:
    - windows/workstation

######## COMMON
- hosts: dc:exchange:iis:cert:fileserver
  roles:
    - windows/servers/common