linux:
  hosts: null
  children:
    attacker:
      hosts: null
    teamserver:
      hosts: null
    redirector:
      hosts: null
windows:
  hosts: null
  children:
    dc:
      hosts:
        dc01:
          ansible_host: 10.10.10.1
    exchange:
      hosts: null
    iis:
      hosts:
        iis01:
          ansible_host: 10.10.10.2
        iis02:
          ansible_host: 10.10.10.3
    cert:
      hosts:
        cert01:
          ansible_host: 10.10.10.4
    fileserver:
      hosts:
        fileserver01:
          ansible_host: 10.10.10.5
    workstation:
      hosts: null
  vars:
    ansible_user: ansible
    ansible_password: Passw0rd!
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 120
    ansible_winrm_read_timeout_sec: 130
    windows_gateway: 10.10.10.10
    windows_mask: 255.255.0.0
    ansible_become_password: Passw0rd!
