---
- include_tasks: pre_checks.yml

- include_tasks: domain.yml
  when: domain_joined == false
  
- include_tasks: shares.yml
  when: shares_exist == false

- include_tasks: "{{ Local_Misconfig_Path }}"
  when: lmisconfigs_exist == false