---
- name: Create PublicVault folder structure
  ansible.windows.win_file:
    path: C:\PublicVault
    state: directory

- name: Create SecretVault folder structure
  ansible.windows.win_file:
    path: C:\SecretVault
    state: directory

- name: Add public share
  ansible.windows.win_share:
    name: PublicVault
    description: Store for shared files here
    path: C:\PublicVault
    list: yes
    full: Administrators
    read: "Authenticated Users"

- name: Add secret share
  ansible.windows.win_share:
    name: SecretVault
    description: Top secret docs!
    path: C:\SecretVault
    list: no
    full: Administrators
    read: Administrators

# TRIED DO THIS WITH win_share but for the love of **** couldnt get it to work
- name: Powershell - Change access rights on PublicVault
  ansible.windows.win_powershell:
    script: |
          $dir = "C:\PublicVault"
          $Acl = Get-Acl -Path "$dir"
          $identity = '{{ Domain }}\{{ Groups | random }}'
          $rights = 'FullControl'
          $inheritance = 'ContainerInherit, ObjectInherit'
          $propagation = 'None'
          $type = 'Allow'
          $ACE = New-Object System.Security.AccessControl.FileSystemAccessRule($identity,$rights,$inheritance,$propagation, $type)
          $Acl.AddAccessRule($ACE)
          Set-Acl -Path "$dir" -AclObject $Acl
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas  

- name: Powershell - Change access rights on SecretVault
  ansible.windows.win_powershell:
    script: |
          $dir = "C:\SecretVault"
          $Acl = Get-Acl -Path "$dir"
          $identity = '{{ Domain }}\{{ Groups | random }}'
          $rights = 'FullControl'
          $inheritance = 'ContainerInherit, ObjectInherit'
          $propagation = 'None'
          $type = 'Allow'
          $ACE = New-Object System.Security.AccessControl.FileSystemAccessRule($identity,$rights,$inheritance,$propagation, $type)
          $Acl.AddAccessRule($ACE)
          Set-Acl -Path "$dir" -AclObject $Acl
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas  