---
- name: Add machine accounts
  ansible.windows.win_powershell:
    script: |
      $computers = '{{ Computers | to_json }}' | ConvertFrom-Json
      foreach ($computer in $computers) {
        if ($computer -notmatch "^dc") {
          New-ADComputer -Name $computer -ErrorAction SilentlyContinue
        }
      }
