---
- name: Add machine accounts
  ansible.windows.win_powershell:
    script: |
      $computers = '{{ Computers | to_json }}' | ConvertFrom-Json
      foreach ($computer in $computers) {
        if ($computer -notmatch "^dc") {
          New-ADComputer -Name $computer -ErrorAction SilentlyContinue
        }
      }

- name: Create computers killswitch file
  ansible.windows.win_file:
    path: C:\users\{{ ansible_facts['user_id'] }}\Documents\computers.txt
    state: touch
