---
- name: Ensure Groups OU is present & protected
  microsoft.ad.ou:
    name: Groups
    path: "{{ DN }}"
    state: present
    protect_from_deletion: true

- name: Add groups
  ansible.windows.win_powershell:
    script: |
      $groups = '{{ Groups | to_json }}' | ConvertFrom-Json
      foreach ($group in $groups) {
        New-ADGroup -Name $group -GroupScope Global -Path "{{ Group_OU }}" `
          -ErrorAction SilentlyContinue
      }
