---
- name: Ensure Groups OU is present & protected
  ansible.windows.win_powershell:
    script: |
      $dn = "{{ DN }}"
      $ouDN = "OU=Groups,$dn"
      try {
        Get-ADOrganizationalUnit -Identity $ouDN -ErrorAction Stop | Out-Null
      } catch {
        New-ADOrganizationalUnit -Name "Groups" -Path $dn -ProtectedFromAccidentalDeletion $true
      }

- name: Add groups
  ansible.windows.win_powershell:
    script: |
      $groups = '{{ Groups | to_json }}' | ConvertFrom-Json
      foreach ($group in $groups) {
        New-ADGroup -Name $group -GroupScope Global -Path "{{ Group_OU }}" `
          -ErrorAction SilentlyContinue
      }

- name: Create groups killswitch file
  ansible.windows.win_file:
    path: C:\users\{{ ansible_facts['user_id'] }}\Documents\groups.txt
    state: touch
