---
- ansible.builtin.include_tasks: pre_checks.yml

- ansible.builtin.include_tasks: domain.yml
  when: not domain_joined

- ansible.builtin.include_tasks: computers.yml
  when: not computers_exist

- ansible.builtin.include_tasks: groups.yml
  when: not groups_exist

- ansible.builtin.include_tasks: users.yml
  when: not users_exist

- ansible.builtin.include_tasks: make_misconfigs.yml
  when: not misconfigs_exist

- ansible.builtin.include_tasks: "{{ Local_Misconfig_Path }}"
  when: not lmisconfigs_exist
