---
- ansible.builtin.include_tasks: "misconfigs/{{ User_Misconfigs | random }}"
  vars:
    selection: "{{ item }}"
  loop: "{{ Usernames }}"

- ansible.builtin.include_tasks: "misconfigs/join_group.yml"
  vars:
    selection: "{{ item }}"
  loop: "{{ Usernames }}"

- ansible.builtin.include_tasks: "misconfigs/{{ Group_Misconfigs | random }}"
  vars:
    selection: "{{ item }}"
  loop: "{{ Groups }}"

- ansible.builtin.include_tasks: "misconfigs/{{ Computer_Misconfigs | random }}"
  vars:
    selection: "{{ item }}$"
  loop: "{{ Computers }}"

- name: Create killswitch file for misconfigs
  ansible.windows.win_file:
    path: C:\users\{{ ansible_facts['user_id'] }}\Documents\misconfigs.txt
    state: touch
