---
## Domain
- name: Checking if domain joined
  set_fact:
    domain_joined: "{{ Domain in ansible_facts['windows_domain'] }}"

### Computers
- name: Check if computer account exists in Active Directory
  block:
    - set_fact:
        computers_exist: false
    - set_fact:
        last_comp: '{{ Computers | last }}'

    - name: Check computers exist
      ansible.windows.win_shell: |
        Get-ADComputer -Filter { Name -eq "{{ last_comp }}" } | Select-Object -ExpandProperty Name
      register: computer_account_result
      ignore_errors: true

    - set_fact:
        computers_exist: true
      when:
        - last_comp in computer_account_result.stdout
        - domain_joined

### Groups
- name: Check if groups exists in Active Directory
  block:
    - set_fact:
        groups_exist: false
    - set_fact:
        last_group: '{{ Groups | last }}'

    - name: Check groups exist
      ansible.windows.win_shell: |
        Get-ADGroup -Filter { Name -eq "{{ last_group }}" } | Select-Object -ExpandProperty Name
      register: group_result
      ignore_errors: true

    - set_fact:
        groups_exist: true
      when:
        - last_group in group_result.stdout
        - domain_joined

### Users
- name: Ensuring users are present
  block:
    - set_fact:
        users_exist: false
    - ansible.windows.win_user:
        name: '{{ Usernames | last }}'
        state: query
      register: user

- name: Set users_exist if users found
  set_fact:
    users_exist: true
  when: "'path' in item.key"
  loop: "{{ lookup('ansible.builtin.dict', user) }}"

### AD Misconfigs
- name: Check for AD misconfigs killswitch file
  block:
    - set_fact:
        misconfigs_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\misconfigs.txt
      register: file_info

    - set_fact:
        misconfigs_exist: true
      when: file_info.stat.exists

### Local Misconfigs
- name: Check for local misconfigs killswitch file
  block:
    - set_fact:
        lmisconfigs_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\lmisconfigs.txt
      register: file_info

    - set_fact:
        lmisconfigs_exist: true
      when: file_info.stat.exists
