---
## Domain
- name: Check if domain joined
  set_fact:
    domain_joined: "{{ Domain in ansible_facts['windows_domain'] }}"

### Computers
- name: Check for computers killswitch file
  block:
    - set_fact:
        computers_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\computers.txt
      register: computers_file

    - set_fact:
        computers_exist: true
      when: computers_file.stat.exists

### Groups
- name: Check for groups killswitch file
  block:
    - set_fact:
        groups_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\groups.txt
      register: groups_file

    - set_fact:
        groups_exist: true
      when: groups_file.stat.exists

### Users
- name: Check for users killswitch file
  block:
    - set_fact:
        users_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\users.txt
      register: users_file

    - set_fact:
        users_exist: true
      when: users_file.stat.exists

### AD Misconfigs
- name: Check for AD misconfigs killswitch file
  block:
    - set_fact:
        misconfigs_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\misconfigs.txt
      register: misconfigs_file

    - set_fact:
        misconfigs_exist: true
      when: misconfigs_file.stat.exists

### Local Misconfigs
- name: Check for local misconfigs killswitch file
  block:
    - set_fact:
        lmisconfigs_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\lmisconfigs.txt
      register: lmisconfigs_file

    - set_fact:
        lmisconfigs_exist: true
      when: lmisconfigs_file.stat.exists
