---
# https://docs.ansible.com/ansible/latest/collections/community/windows/win_domain_user_module.html
- name: Create domain users
  community.windows.win_domain_user:
    name: "{{ item }}"
    password: Passw0rd!
    state: present
  loop: "{{ Usernames }}"