---
- name: Create domain users
  ansible.windows.win_powershell:
    script: |
      $password = ConvertTo-SecureString "Passw0rd!" -AsPlainText -Force
      $users = '{{ Usernames | to_json }}' | ConvertFrom-Json
      foreach ($user in $users) {
        New-ADUser -Name $user -SamAccountName $user `
          -AccountPassword $password -Enabled $true `
          -ErrorAction SilentlyContinue
      }
