---
Exchange_Features:
 - NET-Framework-45-Features
 - NET-WCF-HTTP-Activation45
 - RPC-over-HTTP-proxy
 - RSAT-ADDS
 - RSAT-ADDS-Tools
 - RSAT-Clustering
 - RSAT-Clustering-CmdInterface
 - RSAT-Clustering-Mgmt
 - RSAT-Clustering-PowerShell
 - WAS-Process-Model
 - Web-Asp-Net45
 - Web-ASP-NET45
 - Web-Basic-Auth
 - Web-Client-Auth
 - Web-Digest-Auth
 - Web-Dir-Browsing
 - Web-Dyn-Compression
 - Web-Http-Errors
 - Web-Http-Logging
 - Web-Http-Redirect
 - Web-Http-Tracing
 - Web-ISAPI-Ext
 - Web-ISAPI-Filter
 - Web-Lgcy-Mgmt-Console
 - Web-Metabase
 - Web-Mgmt-Console
 - Web-Mgmt-Service
 - Web-Net-Ext45
 - Web-Request-Monitor
 - Web-Server
 - Web-Stat-Compression
 - Web-Static-Content
 - Web-Windows-Auth
 - Web-WMI
 - Windows-Identity-Foundation

Domain_Controller: "{{ groups['dc'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"