---
# https://learn.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/configure-kerberos-delegation-group-managed-service-accounts
- name: Set constrained delegation
  ansible.windows.win_powershell:
    script: |
      $pairs = '{{ assignments | to_json }}' | ConvertFrom-Json
      foreach ($pair in $pairs) {
        $dn = (Get-ADComputer -Identity $pair.target).DistinguishedName
        Set-ADObject -Identity $dn -Add @{
          "msDS-AllowedToDelegateTo" = @(
            "TIME/$($pair.rand_computer)",
            "TIME/$($pair.rand_computer).{{ Domain }}",
            "TIME/$($pair.rand_computer).{{ Domain }}/{{ Domain }}"
          )
        }
        Set-ADAccountControl -Identity $dn -TrustedForDelegation $false -TrustedToAuthForDelegation $true
      }
