---
# https://www.ired.team/offensive-security-experiments/active-directory-kerberos-abuse/abusing-active-directory-acls-aces
- name: Give GenericWrite over random groups
  ansible.windows.win_powershell:
    script: |
      $pairs = '{{ assignments | to_json }}' | ConvertFrom-Json
      foreach ($pair in $pairs) {
        $Destination = (Get-ADGroup -Identity $pair.rand_group).DistinguishedName
        $Source = (Get-ADComputer -Identity $pair.target).sid
        $ADObject = [ADSI]("LDAP://" + $Destination)
        $adRights = [System.DirectoryServices.ActiveDirectoryRights]"GenericWrite"
        $type = [System.Security.AccessControl.AccessControlType]"Allow"
        $inheritanceType = [System.DirectoryServices.ActiveDirectorySecurityInheritance]"All"
        $ACE = New-Object System.DirectoryServices.ActiveDirectoryAccessRule $Source,$adRights,$type,$inheritanceType
        $ADObject.psbase.ObjectSecurity.AddAccessRule($ACE)
        $ADObject.psbase.commitchanges()
      }
