---
- name: Set DoesNotRequirePreAuth
  ansible.windows.win_powershell:
    script: |
      $targets = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      foreach ($t in $targets) {
        Set-ADAccountControl -Identity $t -DoesNotRequirePreAuth $true
      }
