---
- name: Give GenericWrite over random computers
  ansible.windows.win_powershell:
    script: |
      $pairs = '{{ assignments | to_json }}' | ConvertFrom-Json
      foreach ($pair in $pairs) {
        $Destination = (Get-ADComputer -Identity $pair.rand_computer).DistinguishedName
        $Source = (Get-ADUser -Identity $pair.target).sid
        $ADObject = [ADSI]("LDAP://" + $Destination)
        $adRights = [System.DirectoryServices.ActiveDirectoryRights]"GenericWrite"
        $type = [System.Security.AccessControl.AccessControlType]"Allow"
        $inheritanceType = [System.DirectoryServices.ActiveDirectorySecurityInheritance]"All"
        $ACE = New-Object System.DirectoryServices.ActiveDirectoryAccessRule $Source,$adRights,$type,$inheritanceType
        $ADObject.psbase.ObjectSecurity.AddAccessRule($ACE)
        $ADObject.psbase.commitchanges()
      }
