---
- name: Set SPNs for Kerberoasting
  ansible.windows.win_powershell:
    script: |
      $targets = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      foreach ($t in $targets) {
        setspn -s "${t}svc/workstation01.{{ Domain }}" $t
      }
