---
- ansible.builtin.include_tasks: pre_checks.yml

- ansible.builtin.include_tasks: domain.yml
  when: not domain_joined

- ansible.builtin.include_tasks: "{{ Local_Misconfig_Path }}"
  when: not lmisconfigs_exist
