---
# https://www.ired.team/offensive-security-experiments/active-directory-kerberos-abuse/dump-password-hashes-from-domain-controller-with-dcsync
- name: Give DcSync rights
  ansible.windows.win_powershell:
    script: |
      $targets = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      foreach ($t in $targets) {
        dsacls.exe {{ DN }} /I:T /G "{{ NetBIOS }}\${t}:CA;Replicating Directory Changes"
        dsacls.exe {{ DN }} /I:T /G "{{ NetBIOS }}\${t}:CA;Replicating Directory Changes All"
      }
