---
# https://github.com/PhilKeeble/AWS-RedTeam-ADLab/blob/main/dsc/adlab.ps1

# Tested working: Server 2016
- name: Powershell - Put clear text password in {{ selection }}'s description
  ansible.windows.win_powershell:
    script: |
      $user = (Get-ADUser -Identity {{ selection }}).DistinguishedName
      Set-ADUser -Identity $user -Description "Default Password: Passw0rd!"