---
- name: Put clear text password in description
  ansible.windows.win_powershell:
    script: |
      $targets = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      foreach ($t in $targets) {
        Set-ADUser -Identity $t -Description "Default Password: Passw0rd!"
      }
