---
- name: Add batch to DnsAdmins
  ansible.windows.win_powershell:
    script: |
      $members = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      Add-ADGroupMember -Identity "DnsAdmins" -Members $members
