---
- name: Add users to random groups
  ansible.windows.win_powershell:
    script: |
      $pairs = '{{ assignments | to_json }}' | ConvertFrom-Json
      foreach ($pair in $pairs) {
        Add-ADGroupMember -Identity $pair.rand_group -Members $pair.target -ErrorAction SilentlyContinue
      }
