---
- name: Add batch to Key Admins
  ansible.windows.win_powershell:
    script: |
      $members = '{{ assignments | map(attribute="target") | list | to_json }}' | ConvertFrom-Json
      Add-ADGroupMember -Identity "Key Admins" -Members $members
