---
- name: Change the hostname {{ inventory_hostname }}
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"

- name: Set internal DNS server
  ansible.windows.win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ groups['dc'] | map('extract', hostvars, ['ansible_host']) | list }}"

- name: Powershell - Set static IP address
  ansible.windows.win_powershell:
    script: |
      $if = (Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.Name -like 'Ethernet*' } | Select-Object -First 1).Name
      netsh interface ip set address "$if" static {{ ansible_host }} {{ windows_mask }} {{ windows_gateway }}
  async: 100
  poll: 0
  vars:
    ansible_win_async_startup_timeout: 60

- name: Wait for hosts network
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 5986
    delay: 10
    state: started
  delegate_to: localhost
  register: wait_result

- name: Reboot for hostname change
  ansible.windows.win_reboot:
    reboot_timeout: 3600

- name: Joining {{ inventory_hostname }} to {{ Domain }}
  microsoft.ad.membership:
    dns_domain_name: "{{ Domain }}"
    domain_admin_user: administrator@{{ Domain }}
    domain_admin_password: Passw0rd!
    state: domain
  register: domain_state

- ansible.windows.win_reboot:
    reboot_timeout: 3600
  when: domain_state.reboot_required
