---
# Expand AD Schema
- name: Copy ISO to C:\ - (This may take some time)
  ansible.windows.win_copy:
    src: exchangeserver2016.iso
    dest: C:\
  delegate_to: "{{ Domain_Controller }}"
  connection: winrm
  vars:
    ansible_user: ansible
    ansible_password: Passw0rd!
    ansible_winrm_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

- name: Ensure an ISO is mounted 
  community.windows.win_disk_image:
    image_path: C:\exchangeserver2016.iso
    state: present
  register: disk_image_out
  delegate_to: "{{ Domain_Controller }}"
  connection: winrm
  ignore_errors: true
  vars:
    ansible_user: ansible
    ansible_password: Passw0rd!
    ansible_winrm_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

- name: Set fact for ISO setup.exe path
  set_fact:
    exchange_setup: "{{ disk_image_out.mount_paths[0] }}setup.exe"

- name: Expand AD Schema
  win_package:
    path: "{{ exchange_setup }}"
    arguments: >-
      /PrepareSchema 
      /IAcceptExchangeServerLicenseTerms
    state: present
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas 
  vars:
    ansible_user: ansible
    ansible_password: Passw0rd!
    ansible_winrm_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

- name: Prepare AD for Exchange
  win_package:
    path: "{{ exchange_setup }}"
    arguments: >-
      /PrepareAD
      /OrganizationName:"{{ NetBIOS }}"
      /IAcceptExchangeServerLicenseTerms
    state: present
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas 
  vars:
    ansible_user: ansible
    ansible_password: Passw0rd!
    ansible_winrm_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore