---
# Expand AD Schema
- name: Copy ISO to C:\ - (This may take some time)
  ansible.windows.win_copy:
    src: exchangeserver2016.iso
    dest: C:\

- name: Ensure an ISO is mounted 
  community.windows.win_disk_image:
    image_path: C:\exchangeserver2016.iso
    state: present
  register: disk_image_out
  ignore_errors: true

- name: Set fact for ISO setup.exe path
  set_fact:
    exchange_setup: "{{ disk_image_out.mount_paths[0] }}setup.exe"

- name: Expand AD Schema
  win_package:
    path: "{{ exchange_setup }}"
    arguments: >-
      /PrepareSchema 
      /IAcceptExchangeServerLicenseTerms
    state: present
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas 

- name: Prepare AD for Exchange
  win_package:
    path: "{{ exchange_setup }}"
    arguments: >-
      /PrepareAD
      /OrganizationName:"{{ NetBIOS }}"
      /IAcceptExchangeServerLicenseTerms
    state: present
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas 

