---
- name: Ensure an ISO is mounted 
  community.windows.win_disk_image:
    image_path: C:\exchangeserver2016.iso
    state: present
  register: disk_image_out

- name: Set fact for ISO setup.exe path
  set_fact:
    exchange_setup: "{{ disk_image_out.mount_paths[0] }}setup.exe"

- name: Install Exchange on {{ inventory_hostname }} - (This will take a long time(like ~1.5 hours))
  win_package:
    path: "{{ exchange_setup }}"
    arguments: >-
      /IAcceptExchangeServerLicenseTerms
      /Mode:Install
      /Roles:Mailbox
      /DisableAMFiltering
      /OrganizationName:"{{ NetBIOS }}"
    state: present
  register: pri_exchange_install
  become: yes
  become_user: '{{ NetBIOS }}\administrator'
  become_method: runas  

- name: Reboot Exchange Install
  win_reboot:
   reboot_timeout: 3600
  ignore_errors: true