---
- ansible.builtin.include_tasks: pre_checks.yml

- ansible.builtin.include_tasks: domain.yml
  when: not domain_joined

- ansible.builtin.include_tasks: pre_reqs.yml

- ansible.builtin.include_tasks: exchange_ad.yml
- ansible.builtin.include_tasks: exchange.yml
