---
## Domain
- name: Checking if domain joined
  set_fact:
    domain_joined: "{{ Domain in ansible_facts['windows_domain'] }}"

### Local Misconfigs
- name: Check for local misconfigs killswitch file
  block:
    - set_fact:
        lmisconfigs_exist: false

    - ansible.windows.win_stat:
        path: C:\users\{{ ansible_facts['user_id'] }}\Documents\lmisconfigs.txt
      register: file_info

    - set_fact:
        lmisconfigs_exist: true
      when: file_info.stat.exists
