
---
- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  become: true 
  become_user: root

# Last step
- name: Updating file locations
  ansible.builtin.shell:
      cmd: updatedb
  become: true 
  become_user: root